apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container 
          image: nginx:1.19
    

